### ISSUE TITLE
Uppercase package and symbol names break Allegro modern-mode

### ISSUE THREAD

**Issue by genworks** [mbattyani/cl-typesetting#2]
Hi,

 In hyphenation-fp.lisp, I recommend changing the `defpackage :cl-typesetting-hyphen` to the following: 

```
(defpackage :cl-typesetting-hyphen
  (:use common-lisp)
  (:nicknames :cl-tt-hyph)
  (:export #:language-defined-p
	   #:define-language
	   #:language-loaded-p
	   #:load-language
	   #:language-hyphenation))
```

Otherwise the uppercase strings will break modern-mode Lisps such as Allegro CL mlisp. 

Regards,

 Dave

**Comment by mbattyani** [comment]
Done. Thanks Dave!
